Freezing layer 'model.22.dfl.conv.weight'
WARNING ‚ö†Ô∏è imgsz=[920] must be multiple of max stride 32, updating to [928]
[34m[1malbumentations: [39m[22mBlur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
Plotting labels to runs\detect\train16\labels.jpg...
[34m[1mtrain: [39m[22mScanning C:\Users\PC\Desktop\Freelancer\Aligh-with-arm\synthetics\align-lmk.cache... 2076 images, 0 backgrounds, 0 corrupt: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 2076/2076 [00:00<?, ?it/s]
C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\albumentations\core\composition.py:144: UserWarning: Got processor for bboxes, but no transform to process it.
  self._set_keys()
[34m[1mval: [39m[22mScanning C:\Users\PC\Desktop\Freelancer\Aligh-with-arm\synthetics\align-lmk.cache... 2076 images, 0 backgrounds, 0 corrupt: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 2076/2076 [00:00<?, ?it/s]
[34m[1moptimizer:[39m[22m 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
[34m[1moptimizer:[39m[22m AdamW(lr=0.000909, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
  0%|          | 0/130 [00:00<?, ?it/s]
[34m[1mTensorBoard: [39m[22mmodel graph visualization added ‚úÖ
Image sizes 928 train, 928 val
Using 0 dataloader workers
Logging results to [1mruns\detect\train16
Starting training for 30 epochs...


































































































































       1/30         0G     0.7359     0.9418      1.185        136        928: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 130/130 [19:23<00:00,  8.95s/it]
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

































































































































       2/30         0G     0.5237     0.5943      1.007         97        928: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 130/130 [18:58<00:00,  8.75s/it]
  0%|          | 0/130 [00:00<?, ?it/s]
































       3/30         0G     0.5026     0.5169     0.9577        166        928:  25%|‚ñà‚ñà‚ñå       | 33/130 [04:46<14:02,  8.69s/it]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Freelancer\Aligh-with-arm\synthetics\y8-train-lmk.py", line 7, in <module>
    results = model.train(data=r'align.yaml',
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 601, in train
    self.trainer.train()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 358, in _do_train
    for i, batch in pbar:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\build.py", line 49, in __iter__
    yield next(self.iterator)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 251, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 257, in get_image_and_label
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 157, in load_image
    im = cv2.imread(f)  # BGR
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\Freelancer\\Aligh-with-arm\\synthetics\\align-lmk\\000061.jpg'
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Freelancer\Aligh-with-arm\synthetics\y8-train-lmk.py", line 7, in <module>
    results = model.train(data=r'align.yaml',
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 601, in train
    self.trainer.train()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 208, in train
    self._do_train(world_size)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\trainer.py", line 358, in _do_train
    for i, batch in pbar:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\build.py", line 49, in __iter__
    yield next(self.iterator)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 251, in __getitem__
    return self.transforms(self.get_image_and_label(index))
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 257, in get_image_and_label
    label["img"], label["ori_shape"], label["resized_shape"] = self.load_image(index)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\data\base.py", line 157, in load_image
    im = cv2.imread(f)  # BGR
  File "C:\Users\PC\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\Desktop\\Freelancer\\Aligh-with-arm\\synthetics\\align-lmk\\000061.jpg'